name: Run on push to master BookCart Cypress via browser container
on: 
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        types: [opened, assigned, reopened]
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
        image: cypress/browsers:node-18.15.0-chrome-106.0.5249.61-1-ff-99.0.1-edge-114.0.1823.51-1
    steps:
    - name: Get repository code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Run the tests 
      run: npm run cy:run:bookcart
    - name: Generate mochawesome report
      run: npm run generate:report
      if: failure()||success()
    - name: Save report
      uses: actions/upload-artifact@v3
      with:
        path: mochawesome-report
        name: Test report
      if: failure()||success()
    - name: Save report
      uses: actions/download-artifact@v3
      with:
        name: Test report
      if: failure()||success()